[project]
name = "commandkit"
version = "0.3.1"

############

description = "a standalone library to bring discord.py developer experience to your python applications, focus on building your logic rather then an event manager or command manager"
readme = "README.md"
keywords = ["commands", "python3", "commandkit", "events"]
license = { file = "LICENSE" }
classifiers = [
    "Intended Audience :: Developers",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "License :: OSI Approved :: MIT License",
]

[project.optional-dependencies]
dev = [
    "black",
    "sphinx",
    "sphinx-rtd-theme"
    ]


[tool.setuptools.packages.find]
include = ["commandkit*"]

[project.urls]
Changelog = "https://github.com/programminglaboratorys/commandkit/blob/main/CHANGELOG"
Documentation = "https://commandkit.readthedocs.io/en/latest/"
Homepage = "https://github.com/programminglaboratorys/commandkit"
Issues = "https://github.com/programminglaboratorys/commandkit/issues"